language: node_js
services:
  - postgresql
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c 'CREATE DATABASE bionexo_test;' -U postgres
script:
  - npm install
  - npm test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "qCTlq8GKKN7WeuOA8iV9QJ8SUqZznskEponmSJOz3HYngOWyBP/mFU0eFEdmfYqwnrfVff26SmXbuDI34ESio+5PLcXT/MRLwp4Vj8oZsoYntt1tWAdpYO47VDrAny1o9h3+8cuFtMCi5bC9YVwp97hiquz+Cx/XCuqjXDWitY5SpQ7VkbxaWMRIjenpHEO6aZ1LhHzBkwiphKSWNd9lG0PfY0EZXNn04mgsp7sQgctKedwEXHCNrYgBY9yfNdCwwRxZ4ThmhVdarzdfyo+ChgTkjqRkawrV7sZC6rs0MugGsEoBdXhCozLWKz0t2f/+bUp00KF5I/Ip/N0yfKJtVlTV1qvH2Fza6nH2JBgai9aL3ke3XKSlMN3QqAxWscH38sus1UZpeqsRB5GzRwWtvg3N/QXlYj2zVkmDoC+VKLgHUND85BLMfRe4OrnkWyWjG/G0l32J05qfNrRvd965IIOQngq/A4AYqsiUNoDF8cOxfgbDCdWeIxPVgWluwK0/aRD28/jtINYjp5eNpbBt/eTgs2JxcLafpROJfkLcp5FwfArE+KqqAs483SKXcGSxy5EfUaN8MPfZyFN153rl1M9vIOn5rShic24+RkhDxTD/bwtXMQJMqQuc5/rRSznNMfarnPUDRHCK6YhDwCadYRQK6lmKUBaop6sgQBUPX0A="
