version: '3'

services: 
  app:
    image: adalbertorsilvaje/bionexo-challenge:latest
    build: .
    ports:
      - 3000
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    ports: 
      - 5433