version: '3'

services: 
  app:
    image: adalbertorsilvaje/bionexo-challenge:latest
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=junior
    build: .
    ports:
      - 3000:3000
    depends_on: 
      - db
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_PASSWORD=junior
      - POSTGRES_USER=postgres 
    restart: always
    ports: 
      - 5433:5432